### ISSUE TITLE
Unable to feed the optical model (CRSEO crate) actor with a downrated chain

### ISSUE THREAD

**Issue by rodrigo-romano** [GMTO-Integrated-Modeling/grsim#1]
Unable to create a chain feeding the CRSEO optical model using the downsample feature.
For example, in `ngao-opm` crate (lines 133-134 of [main.rs](https://github.com/GMTO-Integrated-Modeling/grsim/blob/rro-servo-optical/ngao-opm/src/main.rs) in the `rro-servo-optical` branch), the compilation fails if one tries to downsample the chain connecting the M1 & M2 rigid-body motions outputs to the optical model.

**Comment by rconan** [comment]
this is the expected behavior when working with _systems_ like `GmtServoMechanics` where inputs and outputs rates are preset to 1, the solution was to force the input rate of the  `optical_model` to the desired value (8) by introducing the chain `8: optical_model`
